# Generated by Django 5.1.4 on 2024-12-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_nomina', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_video', models.CharField(max_length=50)),
                ('extension_video', models.CharField(max_length=5)),
                ('tamano_videos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.usuario')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.video')),
            ],
        ),
    ]
