# Generated by Django 5.1.4 on 2025-01-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='info_general.usuario'),
        ),
    ]
