# Generated by Django 5.1.4 on 2025-01-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0002_video_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tamano_videos',
            new_name='tamano_video',
        ),
    ]
