# Generated by Django 5.1.4 on 2025-01-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0003_rename_tamano_videos_video_tamano_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioVideo',
        ),
    ]
