# Generated by Django 5.1.4 on 2025-01-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_general', '0004_delete_usuariovideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='usuario',
        ),
        migrations.CreateModel(
            name='UsuarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_general.video')),
            ],
        ),
    ]
